
magic_conch_shell = [
    "It is certain, just relax and it will come",
    "It is decidedly so",
    "Without a doubt",
    "Yes definitely, don't ask anymore for today",
    "You may rely on it",
    "As I see it... yes",
    "Most likely, but you have to take the first step",
    "Outlook is good, do your best",
    "Yes",
    "Signs point to yes, but with some difficulty",
    "Reply hazy, try again after a shower",
    "Ask again later, for now try to relax",
    "Better not tell you now, you'll understand later",
    "Cannot predict now, ask something else",
    "Concentrate, breathe, close your eyes and ask again",
    "Don't count on it, do something else",
    "My reply is no, have a nice day",
    "My Cardboard box says no",
    "**Error 404**: answer not found.",
    "Outlook not so good",
    "Very doubtful, better don't get attached",
    "Never, better give up and be happy",
    "Forget about it, turn on airplane mode for a while",
    "┐( ˘ㅅ˘)┌ I doesn't really care"
]

magic_coin_oracle = [
    "「1」 **`Chien`** : `the vital spirit of heaven`\n*Good fortune is coming your way in anything you do*",
    "「2」 **`K'un`** : `a multiplicity of things`\n*Troubles and problems are solved with little difficulty*",
    "「3」 **`Chun`** : `difficulty getting started`\n*There is a great danger in gossip getting out of hand*",
    "「4」 **`Meng`** : `getting caught`\n*Youthful foolishness. Wasting money. Your life is filled with idle gossip*",
    "「5」 **`Hsu`** : `waiting`\n*Happiness is coming. Commited projects are successful*",
    "「6」 **`Sung`** : `conflict`\n*There are obstacles that block everything you do*",
    "「7」 **`Shih`** : `the mass of humanity`\n*Plans find a favourable response*",
    "「8」 **`Pi`** : `a banding together`\n*Soon here will include a purport for the result to your question.*",
    "「9」 **`Hsiao Ch'u`** : `small involvement`\n*Not a good time to expand. Good time to relax*",
    "「10」 **`Lu`** : `smug self-confidence`\n*Soon here will include a purport for the result to your question.*",
    "「11」 **`Tai`** : `rising above adversity`\n*Relationships enjoy a period of great harmony*",
    "「12」 **`P'i`** : `stagnation`\n*Soon here will include a purport for the result to your question.*",
    "「13」 **`T'ung Jen`** : `people who have affinity with each other`\n*Soon here will include a purport for the result to your question.*",
    "「14」 **`Ta Yu`** : `having great possessions`\n*What you have lost will return to you*",
    "「15」 **`Ch'ien`** : `holding one's tongue`\n*Soon here will include a purport for the result to your question.*",
    "「16」 **`Yu`** : `eagerness to start`\n*Soon here will include a purport for the result to your question.*",
    "「17」 **`Sui`** : `obedient participation`\n*This is a time that favours you*",
    "「18」 **`Ku`** : `inner turmoil`\n*Soon here will include a purport for the result to your question.*",
    "「19」 **`Lin`** : `different classes of people`\n*Soon here will include a purport for the result to your question.*",
    "「20」 **`Kuan`** : `looking, seeing, confronting`\n*Soon here will include a purport for the result to your question.*",
    "「21」 **`Shih Ho`** : `wrathful`\n*The agony of loneliness finds respite*",
    "「22」 **`Pi`** : `grace and beauty`\n*Soon here will include a purport for the result to your question.*",
    "「23」 **`Po`** : `finality of death`\n*Soon here will include a purport for the result to your question.*",
    "「24」 **`Fu`** : `turning back`\n*Even a friend becomes an enemy. You need patience for this time of confusion*",
    "「25」 **`Wu Wang`** : `innocence`\n*Your lover is betraying you, be careful*",
    "「26」 **`Ta Ch'u`** : `big involvement`\n*Clarity emerges where there was confusion*",
    "「27」 **`I`** : `nourishment`\n*There's an excellent person helping you, a mentor*",
    "「28」 **`Ta Kuo`** : `great excess`\n*Soon here will include a purport for the result to your question.*",
    "「29」 **`Kan`** : `the Abysmal`\n*The image of the Abysmal is like seeing a mirage*",
    "「30」 **`Li`** : `clinging`\n*Soon here will include a purport for the result to your question.*",
    "「31」 **`Hsien`** : `something felt in the heart`\n*Soon here will include a purport for the result to your question.*",
    "「32」 **`Heng`** : `constancy`\n*Soon here will include a purport for the result to your question.*",
    "「33」 **`Tun`** : `running away`\n*Soon here will include a purport for the result to your question.*",
    "「34」 **`Ta Chuang`** : `great wisdom`\n*Meetings with friends go smoothly*",
    "「35」 **`Chin`** : `meting the great Man`\n*Soon here will include a purport for the result to your question.*",
    "「36」 **`Ming I`** : `a darkening`\n*Soon here will include a purport for the result to your question.*",
    "「37」 **`Chia Jen`** : `the family type`\n*Soon here will include a purport for the result to your question.*",
    "「38」 **`Kuei`** : `opposition`\n*Soon here will include a purport for the result to your question.*",
    "「39」 **`Chien`** : `grave danger`\n*wwwwtiowwwn*",
    "「40」 **`Hsieh`** : `liberation`\n*Your social life takes-off, suddenly you are very popular*",
    "「41」 **`Sun`** : `loss`\n*Soon here will include a purport for the result to your question.*",
    "「42」 **`I`** : `increase`\n*Misfortune transform into good fortune*",
    "「43」 **`Kuai`** : `determination`\n*Determination gets you everywhere, it reaps you benefits*",
    "「44」 **`Kou`** : `an encounter`\n**",
    "「45」 **`Ts'ui`** : `gathering`\n*Soon here will include a purport for the result to your question.*",
    "「46」 **`Sheng`** : `ascending`\n*Soon here will include a purport for the result to your question.*",
    "「47」 **`K'un`** : `oppression`\n*Soon here will include a purport for the result to your question.*",
    "「48」 **`Ching`** : `the well`\n*Soon here will include a purport for the result to your question.*",
    "「49」 **`Ko`** : `revolution`\n*Soon here will include a purport for the result to your question.*",
    "「50」 **`Ting`** : `the cauldron`\n*Soon here will include a purport for the result to your question.*",
    "「51」 **`Chen`** : `thunder`\n*Influential friends help and protect you*",
    "「52」 **`Ken`** : `stillness`\n*Soon here will include a purport for the result to your question.*",
    "「53」 **`Chien`** : `gradual development`\n*Soon here will include a purport for the result to your question.*",
    "「54」 **`Kuei Mei`** : `marrying girl`\n*Soon here will include a purport for the result to your question.*",
    "「55」 **`Feng`** : `greatness`\n*Soon here will include a purport for the result to your question.*",
    "「56」 **`Lu`** : `the exile`\n*Soon here will include a purport for the result to your question.*",
    "「57」 **`Sun`** : `the wind`\n*Soon here will include a purport for the result to your question.*",
    "「58」 **`Tui`** : `joyousness`\n*Soon here will include a purport for the result to your question.*",
    "「69」 **`Huan`** : `dispersion`\n*Soon here will include a purport for the result to your question.*",
    "「60」 **`Chieh`** : `limitation`\n*Soon here will include a purport for the result to your question.*",
    "「61」 **`Chung Fu`** : `inner truth`\n*Soon here will include a purport for the result to your question.*",
    "「62」 **`Hsiao Kuo`** : `small error/weakness`\n*Soon here will include a purport for the result to your question.*",
    "「63」 **`Chi Chi`** : `completion`\n*Soon here will include a purport for the result to your question.*",
    "「64」 **`Wei Chi`** : `before completion`\n*Sadness. A period of misfortune that lasts 28 days*",
    "「◎」 **`Ling`** : `zero answer`\n*tis' not the best time to ask*\nbecause answers are not received.",
    "「xx」**`Zaici`** : `ask again`\n*Make sure you ask a `yes/no` question,*\nbreathe deeply and ask again."
]

flipping_tables = [
    "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ ︵ ┻━┻\n*tablerus-repellus!*",
    "┻━┻ ︵ ┐( ˘ㅅ˘)┌ \nMeh, that table passed far away!",
    "(╯°□°)╯︵ ┻━┻\nTake this back!",
    "┻━ ︵ ¯\\(｡･益･)┌┛ ︵ ━┻\nTable destroyed!",
    "(ノ `Д´)ノ ┬─┬\nWhy you? Take this!",
    "┬─┬ ノ( º _ ºノ)\nBetter luck next time!",
    "╰(⇀ᗣ↼‶)╯ ︵ ┻━┻\nI ducked that one",
    "︵ ┻━┻ . .･ヾ(。￣□￣)ﾂ\nI ran faster than sound!",
    "!(ﾉ｀◎´)ﾉ ︵ ┻━┻\nTable bounced back at you!",
    "(つ•̀ω•́)つ ︵┬─┬\nNothing can touch me",
    "ヽ( ･∀･)ﾉ┌┛︵ ┻━┻\nI kicked the table back at you!",
    "┻━┻ ︵ (ノ`Д´)ノ\nI dove away!",
    "ヾ(ﾟ∀ﾟ○)ﾂ三ヾ(●ﾟ∀ﾟ)ﾉ\nRunning zig-zag so no table can hit him",
    "┬─┬ ヾ(･д･ヾ)\nTables bow down to **robotsu**'s feet",
    "╭(°ㅂ°)╮┻━┻ ︵╰(°ㅂ°)╯\nWhich one am I? Confusion spell.",
    "┬─┬﻿ ノ( ゜-゜ノ)\nStop messing around with tables and go back to school",
    "(｀´)ゞ ((┻━┻))\nTelekinesis counter-attack",
    "(〜￣っ￣)〜 ︵┻━┻\nLOL, no use trying again...",
    ".·´¯`(>▂\nHow could you hit me?"
]

seven = [
    "0\N{COMBINING ENCLOSING KEYCAP}",
    "1\N{COMBINING ENCLOSING KEYCAP}",
    "2\N{COMBINING ENCLOSING KEYCAP}",
    "3\N{COMBINING ENCLOSING KEYCAP}",
    "4\N{COMBINING ENCLOSING KEYCAP}",
    "5\N{COMBINING ENCLOSING KEYCAP}",
    "6\N{COMBINING ENCLOSING KEYCAP}",
    "7\N{COMBINING ENCLOSING KEYCAP}",
    "8\N{COMBINING ENCLOSING KEYCAP}",
    "9\N{COMBINING ENCLOSING KEYCAP}"
]

guessed_wrong = [
    "Not even close, the right number was:",
    "Better luck next time, the number was:",
    "How could you have known that the number was:",
    "Hmm, well, the right number was:",
    "Not getting any better, the number was:",
    "Right number was:"
]

guessed_right = [
    "You guessed correctly!",
    "I knew you could do it!",
    "You got the right answer!",
    "History will remember you, maybe..."
]

greeting_list = [
    ":flag_us: Howdy friend!",
    ":flag_br: Parabens!",
    ":flag_gb: Morning to you too",
    ":flag_mx: Hola amigo",
    ":flag_fr: 'jour. Pourquoi?",
    ":flag_in: Namaste",
    ":flag_es: En hora buena, oz habeis unido al chat",
    ":flag_ar: Che bolu, tenes un buraco en la saviola?",
    ":flag_ir: Shlom",
    ":flag_ru: Privet, drug, ty kak?",
    ":flag_cr: Pura vida mae",
    ":flag_ni: Vah pueh, bien arrecho",
    ":flag_mx: Orale mi carnalito",
    ":flag_pa: Que sopa olape",
    ":flag_fr: Bonjour, quand je viens ici, vous êtes celui que je vois le plus actif",
    ":flag_kr: What can I say..."
    ":flag_rs: Zdravo prijatelju",
    ":flag_kr: Translation not available."
]

said = [
    "said",
    "expressed",
    "wrote",
    "exclamed",
    "commented",
    "thought out loud",
    "whispered",
    "asserted",
    "uttered",
    "alleged",
    "put about",
    "declaimed",
    "postulated",
    "announced",
    "articulated",
    "babbled",
    "beckoned",
    "cajoled",
    "denoted",
    "crooned",
    "expossed",
    "echoed",
    "faltered",
    "jabbered",
    "implied",
    "grunted",
    "insisted",
    "observed",
    "offered",
    "scoffed",
    "sang",
    "suggested",
    "teased",
    "voiced out",
    "yelped",
    "whined",
    "wondered",
    "roared",
    "demanded",
    "leered"
]

adj = [
    "firmly",
    "calmly",
    "eloquently",
    "suddenly",
    "loudly",
    "quietly",
    "to herself",
    "impatiently",
    "succinctly",
    "crisply",
    "clearly",
    "easily",
    "rightly",
    "fluently",
    "diffusely",
    "emphatically",
    "formally",
    "incoherently"
]
